### ISSUE TITLE
📦 Bootstrap Version Issues

### ISSUE THREAD

**Issue by VividWombat** [EhanAhamed/nord-bootstrap#5]
**Please describe what you would like to be changed or improved**
please include the version of bootstrap / nord that your work is based on

**Additional context**
your work seems to be using boostrap 4. bootstrap 5 has a lot of breaking changes, so its useful to know what you're using. especially when you need to include bootstrap js, jquery, or popper as well as css. anyone familiar with boostrap will know to use js if needed. just helps to use the right major version

also useful to know which nord release you base the work on, just in case something changes

**Ping @SaberTooth-Studios**

**Comment by SaberTooth-Studios** [comment]
Hai, @VividWombat 

This repo is based on bootstrap 5.1.3, which is the latest release as of right now. This repo doesn't use the actual nord installation method explained in their docs and instead just copies the color codes included in their official website, so updates to the functionality of nordthem's repo will not effect this repo. The colors used in this repo are from version 0.23.0, the latest release.

I'll update the readme and the changelog of each release to include the versions of nord and bootstrap!

Thanks for opening this isssue, cya later!

**Comment by VividWombat** [comment]
did you migrate from 4 to 5 ? I'm confused, as stuff like close was renamed to btn-close, but you have .close.

**Comment by SaberTooth-Studios** [comment]
Hewwo again!

The tool I used, and recommend to any contributors is bootstrap.build, and they claim that it uses bootstrap 5.1.3, the files were not manually written and were just generated by bootstrap.build

It seems like the variables.scss file's syntax is a mix of bootstrap 4 and 5, that is why I recommend using the css and minified css files in projects since seem to be in v5.1.3

You shouldn't use the variables.scss file for your projects and it should only be used for editing the colors using bootstrap.build, since the variables.scss file is incompatible with both bootstrap 4 and 5 as its a mix of the syntax, however its still readable by bootstrap.build and can be compiled into compatible bootstrap 5 css files.

If you need to use scss, then you can use "[nordstrap](https://github.com/madelyneriksen/nordstrap)", a different repo made by "madelyneriksen" which uses scss.

I will further research the versions before including versioning info, thanks for opening this issue, cya!

**Comment by SaberTooth-Studios** [comment]
Hai again, @VividWombat!

After finding [bootstrap.build's github repo](https://github.com/bootstrap-build/bootstrap.build), I see that it claims that they use bootstrap v4.0, which is different from what they say on the actual website, over there it claims that they use bootstrap 5, but their github repo says otherwise (to put it simply: we've been tricked backstabbed and quite possibly bamboozled)

I have opened [an issue on their repository](https://github.com/bootstrap-build/bootstrap.build/issues/39), and **for the time being; this repo is for bootstrap v4**,
I now plan on finding an alternative to bootstrap.build or I might completly remake this repo to have the files be manually edited from the original, since I have lost my trust in bootstrap.build.

Again, thanks for opening this issue, I will try to fix it as soon as possible!

**Comment by SaberTooth-Studios** [comment]
Hai *again*, @VividWombat!

Just another update: I'm planning to migrate to [Themestr](https://themestr.app/), which uses bootstrap v5.0.1, although that's not the latest release, its close enough to not have too many breaking changes, and unlike [bootstrap.build](https://bootstrap.build/), Themestr doesn't lie about versions and seems to be updated regularly and maintained well. For the moment, this repo uses Bootstrap v4.0, at least until I migrate to Themestr. The `themestr` branch is where the work in progress migration is.

**Comment by SaberTooth-Studios** [comment]
Hai *again* @VividWombat!

I have decided that manually editing values and then compiling them is the best and most reliable method, this repository will no longer use bootstrap.build, and will instead have contributors manually edit color values in their preferred code editor. This change will mean that this repository will use bootstrap v5.1.3, and this also means the entire repo has to be rewritten (although it shouldn't take too long to do so).

I will notify you when I am done migrating, but for the time being this repo is for bootstrap v4.0

**Comment by GwynethLlewelyn** [comment]
BTW, on the `v5` branch, the link to a `WorkInProgressREADME.md` gives a `404` 😼

Count me in on the list of people interested in having a working Nord Bootstrap theme :-)

**Comment by SaberToothed-Dev** [comment]
Hi there, @GwynethLlewelyn!

Thanks for your interest in this project! I haven't worked on it recently, because I was busy with other stuff, but I'm going to start working on it again soon! And thanks for pointing out that error, I'll fix it right now!

**Comment by EhanAhamed** [comment]
Hi again, @GwynethLlewelyn!

I've now finished completely restructuring the repository and build tools to use the compiling system reccomended by bootstrap, the project now uses Bootstrap v5.2.0-beta1, which is the latest release of bootstrap!

If you have any further questions please feel free to ask and/or re-open this issue!

**Comment by EhanAhamed** [comment]
Also it seems I have turned into a ghost 😱😱 
![screenshot](https://user-images.githubusercontent.com/98765025/177205757-93136160-0365-410d-ba1b-284ad66cce3e.png)
